version: "3"
services:
  db:
    image: postgres:16.1-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Taipei
      PGTZ: Asia/Taipei
    ports:
      - 5435:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - go-docker-net
  app:
    build:
      dockerfile: ./deployments/local/backend/Dockerfile
      context: .
    volumes:
      - ./:/app
      - $HOME/.aws:/root/.aws
    ports:
      - 8080:8080
      - 4040:4040
    depends_on:
      - db
    networks:
      - go-docker-net
    env_file:
      - .env
  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./deployments/local/redis/users.acl:/etc/redis/users.acl
      - ./deployments/local/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - go-docker-net
  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./deployments/local/nginx/conf.d/:/etc/nginx/conf.d
      - ${FRONTEND_DIR}/dist/spa:/app
    networks:
      - go-docker-net

networks:
  go-docker-net:

volumes:
  db:
