version: '3'
services:
  db:
    image: postgres:16.1-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Taipei
      PGTZ: Asia/Taipei
    ports:
      - 5435:5432
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - go-docker-net
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
        - go-docker-net
  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/users.acl:/etc/redis/users.acl
    networks:
        - go-docker-net

networks:
  go-docker-net:

volumes:
  db:
