name: Build and upload to S3

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build -o ${{ vars.APP_NAME }}

      - name: Compression
        run: tar -czvf ${{ vars.APP_NAME }}.tgz ${{ vars.APP_NAME }} appspec.yml scripts musical_wiki.service

      - name: Upload to S3
        run: aws s3 cp ./${{ vars.APP_NAME }}.tgz s3://${{ vars.S3_BUCKET }}/${{ vars.APP_NAME }}.tgz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION  }}

      - name: Deploy to EC2
        run: |
          aws deploy create-deployment \
          --application-name ${{ vars.APP_NAME }} \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name ${{ vars.CODEDEPLOY_DEV_GROUP }} \
          --s3-location bucket=${{ vars.S3_BUCKET }},bundleType=tgz,key=${{ vars.APP_NAME }}.tgz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION  }}
